controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint2
      - joint3
      - joint5
      - joint6
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - joint7
initial:  # Define initial robot poses per group
  - group: arm
    pose: test1
  - group: hand
    pose: hand_close